### ISSUE TITLE
Build dependencies are built with hostPlatformCpu and hostPlatformFeatures

### ISSUE THREAD

**Issue by philipstears** [cargo2nix/cargo2nix#129]
We had an interesting issue related to my PR https://github.com/tenx-tech/cargo2nix/pull/119.

Everything built fine on our own build servers, and we got a nice CPU optimized asset out of the remote end. But then a customer tried to build it on their own machine and the build failed with SIGILL.

It transpires, that we've got the following dependency chain: `our code -> clap -> indexmap`, and it is the compilation of `indexmap` that was failing.

After some investigation, it turns out that `indexmap` uses a crate called `autocfg` as part of its build script:

https://github.com/bluss/indexmap/blob/master/build.rs#L4

So although the build script gets built with a different set of flags to crates, `autocfg` is just a regular crate and gets built with the same `hostPlatformCpu` and `hostPlatformFeatures` as any other crate, which then meant that the build script binary couldn't be run on the customer's build server because it didn't have those instruction sets.

I figured that was something worth having a conversation about.

One potential solution I could see is to have crates have both build and host variants in `Cargo.nix` and then having the buildDependencies refer to the build variant instead of the host variant.

I apologize if an issue isn't the right place to discuss this, if there's a better place, I'll happily discuss it there :)

**Comment by ebkalderon** [comment]
Interesting find, @philipstears! I wonder if this was what @trha was referring to in the original PR discussion regarding host vs. build platform CPU/features. 😄 Can you confirm if this is the case, @trha?

We are holding off on releasing 0.9.0 for now since there are a couple open PRs that also need review, so there is some time to merge in further changes and fixes to the `target-cpu` integration.

**Comment by pcpthm** [comment]
I was cross-compiling to a different system (x86_64 -> aarch64) and I also had a similar issue of build-dependency not compiling. I have solved my issue with this code:

```nix
let mk = pkgs:
pkgs.rustBuilder.makePackageSet {
    inherit packageFun;
    inherit (pkgs.buildPackages) cargo rustc;
    buildRustPackages = mk pkgs.pkgsBuildBuild;
}; in mk pkgs
```

I'm still learning Nix and I'm not very confident but in this code: <https://github.com/tenx-tech/cargo2nix/blob/7980d189b194bc8dd24bb95edc4fb4df1fe7b0c0/overlay/make-package-set/simplified.nix#L28-L31> shouldn't we use `pkgsBuildBuild` instead of `buildPackages` (= `pkgsBuildHost`) as we want to run build scripts locally?

**Comment by psionic-k** [comment]
Please take a look at #214.  We're building build.rs scripts just fine in cross on Linux for aarch64-multiplatform (and a few others work)

I'm going to allow that PR to close this issue because if it was still broken, I would not be able to succeed at that cross compile.

I did make a curious change to an offset here:

https://github.com/cargo2nix/cargo2nix/pull/214/files#diff-bb91a7e98aa2be8fd650b55e21949c2c356307162ccd49240c129df750e6531cR16-R28

Target should almost never be used.  Cross compiling can almost 100% be described with just build & host.  Target is supposed to be an implementation detail.
