### ISSUE TITLE
Rust 1.47 - Cannot parse v2 Lockfile Format

### ISSUE THREAD

**Issue by cryptoquick** [cargo2nix/cargo2nix#145]
So, the latest Rust version got pushed to stable last night, which includes a new lockfile format, and it breaks all our builds. We were able to fix it by replacing `stable` with `1.46.0`, but that's not ideal.

The error we got was:
`error: failed to parse lock file at: /build/bitflags-1.2.1/Cargo.lock`

It wasn't just bitflags, there were several packages that broke, but that's just an example.

**Comment by ebkalderon** [comment]
Thanks for reporting this, @cryptoquick! No worries, I can regenerate the lockfile with the latest stable and make it part of the next release.

**Comment by ebkalderon** [comment]
@psionic-k I think this may increase the urgency of resolving #110. In theory, we could simply regenerate the `Cargo.lock` under a newer version of `cargo` and push it to `master`, but then `cargo2nix` would not be able to bootstrap itself because it links against an older version of `cargo`. :disappointed: PR #137 was supposed to resolve this, but it has gone stale due to some strange compilation issues on Darwin.

**Comment by ebkalderon** [comment]
I might give it another go today, seeing as I finally have time!

**Comment by psionic-k** [comment]
You will likely get to the mac issues first.  I need to provision my Apple machine before I can jump in that race.

**Comment by ebkalderon** [comment]
Sounds good! I've just switched over from my Linux machine to my Mac to give it a try.
