### ISSUE TITLE
cargo2nix misses symlinks within workspace

### ISSUE THREAD

**Issue by drozdziak1** [cargo2nix/cargo2nix#188]
I'm trying to build `solana-frozen-abi-macro` which has a build.rs that sets some `cfg` values depending on current toolchain (via `rustc_version`) in its `build.rs` https://github.com/solana-labs/solana/blob/master/frozen-abi/macro/Cargo.toml

 The cause is that the build.rs is a symlink (to `../build.rs`) and lack of the build.rs does not really confuse cargo at a lower level.

Looks like a bad case of NixOS/nix#1232 - can I do anything to help make a failure like this more apparent?

**Comment by psionic-k** [comment]
If the build.rs you want is present and just in the wrong place, you can likely use an override of the unpack or build phase to massage the sources into the correct place before nix misses them.  You can do this for a single dependency similar to here:


https://github.com/cargo2nix/cargo2nix/blob/master/overlay/overrides.nix#L132-L145

**Comment by psionic-k** [comment]
I believe the same issue will affect a crate that references workspace files or files above the workspace but still in the flake.  The proper solution may be to build each crate with the entire workspace source, but having patched out the higher up Cargo.toml's so that cargo doesn't attempt to build the crate with full workspace knowledge.

We could automatically patch some things, but it's likely fragile since paths can be generated through build.rs etc.

As far as how cargo2nix pulls apart dependencies and provides the build information via `.link-flags` and other intermediate files, they still have to be in consistent locations.

Really the change should amount to building workspace crates with a path offset, the full workspace source, and patching out Cargo.toml files in any parent directories.

**Comment by psionic-k** [comment]
https://github.com/cargo2nix/cargo2nix/issues/173

**Comment by psionic-k** [comment]
Think I'm going to add the entire workspace as a source instead of using subpaths as the source.  Performing the offset before running cargo is just another one liner.  Will require modifying the Cargo.nix and overlay.  That would fix the bulk of #173 and this issue.
