### ISSUE TITLE
Bare metal example with cross compile

### ISSUE THREAD

**Issue by drozdziak1** [cargo2nix/cargo2nix#190]
I'd like to build for a bare-metal crate for a different architecture. How do I pick the arch without having nix flip out about choosing which gcc to use?

**Comment by ollie-etl** [comment]
How are you building?

**Comment by psionic-k** [comment]
```
        pkgs = import nixpkgs {
          inherit system;
          crossSystem = {
              config = "x86_64-unknown-linux-musl";
          };
          overlays = [
            (import "${cargo2nix}/overlay")
            rust-overlay.overlay
          ];
        };
```

Works in release-0.9.1 branch.  You can manually configure system & crossSystem instead of using flake-utils `forEachSystem` and get more control.  The `cc` and `rustc` will all be from that nixpkgs, so it's all ready to go up to the extent that the hostPlatform you're after is currently building successfully.

**Comment by psionic-k** [comment]
See #214 to get some ideas.

I would feel more comfortable if something broke.  It's a black box to me until I spend more time on all the host offsets.

> ick the arch without having nix flip out about choosing which gcc to use?
As long as you don't need stdenv on your host, which only happens if you try to "cross" compile on the host for the host (there is no such meaningful offset), nix will not need a gcc and all that on the host.

You will need a stdenv on your build platfrom to build native stuff for `depsBuildBuild` and  one that can _target_ the host if you need any gcc outputs linked into your binary outputs for your host.

If all of the dependencies on the host are rlibs, that means you don't need the `depsBuildHos`t gcc, the one that would target your host.

**Comment by psionic-k** [comment]
#214 is just about complete.  If you can provide a bare metal example, I can probably get it to build with an arbitrary target.  Something I need some examples for is how the Rust toolchain might be selected from the overlay with one target but then configured to output host binaries for weird vendor targets.

**Comment by psionic-k** [comment]
> How do I pick the arch without having nix flip out about choosing which gcc to use?

Don't _depend_ on gcc for that host -> target.  This is really about categorizing all dependencies correctly.

We may need support for picking a different linker, one that is available on the build platform and can emit code for the host.  This is really just #232 though.

Using a rust toolchain with std available shouldn't cause issues?  I wouldn't expect it, but correct me if I'm wrong.

Closing for #232 since linker customization should cover most cases.
