### ISSUE TITLE
Executables not wrapped when using bin output

### ISSUE THREAD

**Issue by FlorentBecker** [cargo2nix/cargo2nix#245]
I'm using cargo2nix to build an executable which depends on `qt`. I use the following to run `wrapQtApps` on the executable built by cargo2nix:
```
(pkgs.rustBuilder.rustLib.makeOverride {
              name = "my_crate_using_qt";
              overrideAttrs = drv: {
                propagatedNativeBuildInputs = drv.propagatedNativeBuildInputs or [ ] ++ [
                  pkgs.qt5.qtbase.dev pkgs.qt5.qtbase pkgs.qt5.wrapQtAppsHook
                ];
              };
            })
```

Then `(rustPkgs.workspace.my_crate_using_qt {})` contains the wrapped executable, but `(rustPkgs.workspace.my_crate_using_qt {}).bin` contains the raw executable. I'd expect both of them to contain the wrapped executable.

**Comment by psionic-k** [comment]
IIRC... because `bin` is a distinct derivation in Nix, you might be able to define overrides for that specific output.

See the sections on wrapping here https://nixos.wiki/wiki/Nix_Cookbook

The overrides for building the crates are able to do basically anything, which you don't need for the `wrapQtAppsHook` stuff to operate correctly.

That's my guess.  Let me know how it goes

**Comment by psionic-k** [comment]
Beautiful.  Closing.  Although now I'm thinking of adding some shortcuts for more kinds of overrides.
