### ISSUE TITLE
Need to be able to specify Cargo feature flags

### ISSUE THREAD

**Issue by torhovland** [cargo2nix/cargo2nix#285]
For example, I need to be able to build using these flags:

```
cargo build -Z build-std=panic_abort,std
```

**Comment by psionic-k** [comment]
This is related to #232 and all of these issues of flags and options need a comprehensive approach.

Enough small increments have accumulated at this point for me to feel comfortable replacing the guts of mkcrate.nix with a better structured builder and nix API.

**Comment by psionic-k** [comment]
https://github.com/cargo2nix/cargo2nix/pull/292/commits/e2112346cebeaff428cf9c5dd92abc80ab0e237b

More or less what is asked for.

I'm going to do a  refactor on this soon because there's obviously a single structure, and the user provided arguments can be mapped into such a structure and avoid having to update the signatures changes for plumbing.
