### ISSUE TITLE
Improve localPatterns

### ISSUE THREAD

**Issue by workflow** [cargo2nix/cargo2nix#36]
Suggest splitting this:

```
    localPatterns = [
      ''^(src)(/.*)?''
      ''^(migrations)(/.*)?''
      ''^(proto)(/.*)?''
      ''[^/]*\.(rs|toml)$''
    ];
```

...into two lists of
`includeLocalFiles`
`includeLocalDirs`

**Comment by ebkalderon** [comment]
Definitely an interesting possibility! For the time being, the local pattern described can be simplified to a one-liner using the current model:

```
localPatterns = [ ''^(src|proto|migrations)(/.*)?'' ''[^/]*\.(rs|toml)$'' ];
```

Hopefully this makes your current experience a bit more manageable in the short term.

**Comment by ebkalderon** [comment]
@trha @eupn @snawaz What would you guys think about potentially honoring the [`includes`/`excludes`](https://doc.rust-lang.org/cargo/reference/manifest.html?highlight=exclude#the-exclude-and-include-fields-optional) fields in the `Cargo.toml` for this instead of providing a separate `localPatterns` filter in the `default.nix`? Any thoughts?

**Comment by snawaz** [comment]
> @trha @eupn @snawaz What would you guys think about potentially honoring the [`includes`/`excludes`](https://doc.rust-lang.org/cargo/reference/manifest.html?highlight=exclude#the-exclude-and-include-fields-optional) fields in the `Cargo.toml` for this instead of providing a separate `localPatterns` filter in the `default.nix`? Any thoughts?

I think that's a good idea. It is used by `cargo publish` command as well. More consistent solution across tools.

**Comment by psionic-k** [comment]
```nix
    localPatterns = [ ''^(src|ctrl-gfx|asus-nb|asus-nb-ctrl|asus-notify|tests|templates)(/.*)?'' ''[^/]*\.(rs|toml)$'' ];
```
Beautiful isn't it?

Currently local patterns does nothing when packaging external sources because it can't.  Git sources aren't in the store and `lib.sourceByRegex` only works on files in the store.  The default setting frequently breaks on crate layouts besides the most basic ones.

Let's just get rid of this API and let the user provide `workspaceSrc` processed however they desire.

**Comment by psionic-k** [comment]
Unpack phase override (still investigating why `packageOverrides` didn't work for adding another `propagatedBuildInput` yesterday) is probably the best way to remove some sources that cause an issue.  I think I'll note that `localPatterns` is only used for local builds.  It's probably too restrictive by default.  What we really want to avoid is copying the target directory(s) into the store as source
